name = "tiny-todo-api"
main = "src/worker/index.ts"
compatibility_date = "2026-03-25"

[build]
command = "npm run ui:build"

[assets]
binding = "ASSETS"
directory = "./dist/client"

[triggers]
crons = ["0 0 * * *"]

[[d1_databases]]
binding = "DB"
database_name = "tiny-todo-api"
database_id = "b9cd1e9b-10be-4408-b113-f1fd2943a780"
migrations_dir = "drizzle/migrations"
