import { afterEach, describe, expect, it } from "vitest";
import worker from "../src/worker/index";
import { createWorkerTestContext, type WorkerTestContext } from "./helpers/worker-test-context";

const contexts: WorkerTestContext[] = [];

afterEach(async () => {
  while (contexts.length > 0) {
    const context = contexts.pop();
    if (context) {
      await context.cleanup();
    }
  }
});

const newContext = async (): Promise<WorkerTestContext> => {
  const context = await createWorkerTestContext();
  contexts.push(context);
  return context;
};

const apiRequest = async (
  context: WorkerTestContext,
  pathName: string,
  init: RequestInit = {},
  auth: "valid" | "invalid" | "none" = "valid"
): Promise<Response> => {
  const headers = new Headers(init.headers);
  if (auth === "valid") {
    headers.set("authorization", `Bearer ${context.apiToken}`);
  }
  if (auth === "invalid") {
    headers.set("authorization", "Bearer not-the-right-token");
  }
  if (init.body && !headers.has("content-type")) {
    headers.set("content-type", "application/json");
  }

  return worker.fetch(new Request(`http://unit.test${pathName}`, { ...init, headers }), context.env);
};

const readJson = async <T>(response: Response): Promise<T> => {
  return (await response.json()) as T;
};

describe("worker integration", () => {
  it("enforces bearer auth for protected endpoints", async () => {
    const context = await newContext();

    const missingTokenResponse = await apiRequest(context, "/tasks", { method: "GET" }, "none");
    expect(missingTokenResponse.status).toBe(401);
    await expect(readJson<{ error: string }>(missingTokenResponse)).resolves.toEqual({ error: "missing bearer token" });

    const invalidTokenResponse = await apiRequest(context, "/tasks", { method: "GET" }, "invalid");
    expect(invalidTokenResponse.status).toBe(401);
    await expect(readJson<{ error: string }>(invalidTokenResponse)).resolves.toEqual({ error: "invalid bearer token" });
  });

  it("supports task CRUD lifecycle", async () => {
    const context = await newContext();

    const createResponse = await apiRequest(context, "/tasks", {
      method: "POST",
      body: JSON.stringify({ title: "Write integration tests", note: "baseline", dueDate: "2026-04-01" })
    });
    expect(createResponse.status).toBe(201);
    const created = await readJson<{ task: { id: string; title: string; note: string | null; status: string; dueDate: string | null } }>(
      createResponse
    );
    expect(created.task.title).toBe("Write integration tests");
    expect(created.task.status).toBe("open");

    const listOpenResponse = await apiRequest(context, "/tasks?status=open&limit=50", { method: "GET" });
    expect(listOpenResponse.status).toBe(200);
    const listedOpen = await readJson<{ tasks: Array<{ id: string; title: string }> }>(listOpenResponse);
    expect(listedOpen.tasks).toHaveLength(1);
    expect(listedOpen.tasks[0]?.id).toBe(created.task.id);

    const patchResponse = await apiRequest(context, `/tasks/${created.task.id}`, {
      method: "PATCH",
      body: JSON.stringify({ note: "updated note", dueDate: "2026-04-03" })
    });
    expect(patchResponse.status).toBe(200);
    const patched = await readJson<{ task: { note: string | null; dueDate: string | null } }>(patchResponse);
    expect(patched.task.note).toBe("updated note");
    expect(patched.task.dueDate).toBe("2026-04-03");

    const completeResponse = await apiRequest(context, `/tasks/${created.task.id}/complete`, { method: "POST" });
    expect(completeResponse.status).toBe(200);
    const completed = await readJson<{ task: { status: string; completedAt: string | null } }>(completeResponse);
    expect(completed.task.status).toBe("done");
    expect(completed.task.completedAt).not.toBeNull();

    const listDoneResponse = await apiRequest(context, "/tasks?status=done&limit=50", { method: "GET" });
    expect(listDoneResponse.status).toBe(200);
    const listedDone = await readJson<{ tasks: Array<{ id: string; status: string }> }>(listDoneResponse);
    expect(listedDone.tasks).toHaveLength(1);
    expect(listedDone.tasks[0]?.id).toBe(created.task.id);
    expect(listedDone.tasks[0]?.status).toBe("done");
  });

  it("materializes recurrence backlog and advances next run date", async () => {
    const context = await newContext();

    const createRuleResponse = await apiRequest(context, "/recurrence-rules", {
      method: "POST",
      body: JSON.stringify({
        titleTemplate: "Daily recurring",
        noteTemplate: "autogenerated",
        cadence: "daily",
        interval: 1,
        anchorDate: "2026-01-01"
      })
    });
    expect(createRuleResponse.status).toBe(201);
    const createRuleBody = await readJson<{ recurrenceRule: { id: string; nextRunDate: string } }>(createRuleResponse);
    expect(createRuleBody.recurrenceRule.nextRunDate).toBe("2026-01-01");

    const firstMaterialize = await apiRequest(context, "/jobs/materialize-recurrence", {
      method: "POST",
      body: JSON.stringify({ date: "2026-01-03" })
    });
    expect(firstMaterialize.status).toBe(200);
    const firstMaterializeBody = await readJson<{ ok: boolean; created: number; rulesProcessed: number }>(firstMaterialize);
    expect(firstMaterializeBody).toEqual({ ok: true, created: 3, rulesProcessed: 1 });

    const listAllTasksResponse = await apiRequest(context, "/tasks?status=all&limit=50", { method: "GET" });
    expect(listAllTasksResponse.status).toBe(200);
    const listAllTasksBody = await readJson<{
      tasks: Array<{ dueDate: string | null; recurrenceRuleId: string | null; title: string; note: string | null }>;
    }>(listAllTasksResponse);
    expect(listAllTasksBody.tasks).toHaveLength(3);
    expect(listAllTasksBody.tasks.map((task) => task.dueDate)).toEqual(["2026-01-01", "2026-01-02", "2026-01-03"]);
    expect(listAllTasksBody.tasks.every((task) => task.recurrenceRuleId === createRuleBody.recurrenceRule.id)).toBe(true);

    const listRulesResponse = await apiRequest(context, "/recurrence-rules", { method: "GET" });
    expect(listRulesResponse.status).toBe(200);
    const listRulesBody = await readJson<{ recurrenceRules: Array<{ id: string; nextRunDate: string }> }>(listRulesResponse);
    expect(listRulesBody.recurrenceRules[0]?.id).toBe(createRuleBody.recurrenceRule.id);
    expect(listRulesBody.recurrenceRules[0]?.nextRunDate).toBe("2026-01-04");

    const secondMaterialize = await apiRequest(context, "/jobs/materialize-recurrence", {
      method: "POST",
      body: JSON.stringify({ date: "2026-01-03" })
    });
    expect(secondMaterialize.status).toBe(200);
    const secondMaterializeBody = await readJson<{ ok: boolean; created: number; rulesProcessed: number }>(secondMaterialize);
    expect(secondMaterializeBody).toEqual({ ok: true, created: 0, rulesProcessed: 0 });
  });
});
